#!/bin/bash
# Tutorial 6: Advanced Vulkan Features for ML

echo "=== Tutorial 6: Advanced Vulkan Features ==="
echo ""

python3 << 'EOF'
print("Advanced Vulkan Features for ML Acceleration:")
print("")

print("=" * 55)
print("1. PUSH CONSTANTS")
print("=" * 55)
print("   • Fast path for small data (< 128 bytes)")
print("   • No buffer allocation needed")
print("   • Updated per-dispatch without rebinding")
print("")
print("   Use cases:")
print("   • Passing tensor dimensions")
print("   • Stride/padding values")
print("   • Activation parameters (alpha, beta)")
print("")
print("   GLSL Example:")
print("   layout(push_constant) uniform PushConstants {")
print("       uint width;")
print("       uint height;")
print("       float scale;")
print("   } params;")
print("")
print("   Available shaders:")
print("   • add_shader_with_push_constants.spv")
print("   • add_shader_unstructured_push_constants.spv")
print("")

print("=" * 55)
print("2. DESCRIPTOR SETS & BINDINGS")
print("=" * 55)
print("   • Bind multiple buffers/images to shader")
print("   • Set 0: Typically input tensors")
print("   • Set 1: Typically output tensors")
print("   • Set 2: Weights/constants")
print("")
print("   Layout pattern for ML:")
print("   layout(set=0, binding=0) buffer InputA { float data[]; };")
print("   layout(set=0, binding=1) buffer InputB { float data[]; };")
print("   layout(set=0, binding=2) buffer Output { float data[]; };")
print("")
print("   Best practices:")
print("   • Group frequently updated descriptors")
print("   • Use descriptor indexing for dynamic access")
print("   • Pool descriptors for efficient allocation")
print("")

print("=" * 55)
print("3. COMPUTE PIPELINE MANAGEMENT")
print("=" * 55)
print("   • VkComputePipelineCreateInfo setup")
print("   • Pipeline cache for fast recreation")
print("   • Specialization constants for compile-time opts")
print("")
print("   Specialization constants example:")
print("   layout(constant_id = 0) const uint BLOCK_SIZE = 64;")
print("   layout(constant_id = 1) const bool USE_FP16 = false;")
print("")
print("   Benefits:")
print("   • Compiler optimizations per variant")
print("   • Single shader source, multiple configs")
print("   • ~10-20% performance gains")
print("")

print("=" * 55)
print("4. SYNCHRONIZATION PRIMITIVES")
print("=" * 55)
print("   Memory Barriers:")
print("   • VK_ACCESS_SHADER_WRITE_BIT -> VK_ACCESS_SHADER_READ_BIT")
print("   • Required between dependent dispatches")
print("   • Use buffer memory barriers for fine control")
print("")
print("   Execution Barriers:")
print("   • VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT")
print("   • Ensures previous dispatch completes")
print("   • Use vkCmdPipelineBarrier()")
print("")
print("   Best practices:")
print("   • Minimize barriers (batch operations)")
print("   • Use correct granularity")
print("   • Profile barrier overhead")
print("")

print("=" * 55)
print("5. WORKGROUP OPTIMIZATION")
print("=" * 55)
print("   Workgroup sizing strategy:")
print("   • Apple Silicon: 32 threads (1 wave)")
print("   • Typical ML: 64, 128, or 256 threads")
print("   • Match to tensor dimensions")
print("")
print("   Dispatch patterns:")
print("   layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;")
print("")
print("   Tiled 2D (for images):")
print("   layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;")
print("")
print("   Memory access patterns:")
print("   • Coalesced access: threads access contiguous memory")
print("   • Shared memory: local_size_x * sizeof(float) bytes")
print("   • Avoid bank conflicts in shared memory")
print("")

print("=" * 55)
print("6. SUBGROUP OPERATIONS (SIMD)")
print("=" * 55)
print("   • Wave-level parallelism")
print("   • Apple Silicon: 32 threads/subgroup")
print("   • No shared memory needed for reductions")
print("")
print("   Key operations:")
print("   • subgroupAdd() - Fast parallel sum")
print("   • subgroupMax() - Parallel max reduction")
print("   • subgroupBroadcast() - Share value across threads")
print("   • subgroupShuffle() - Cross-lane data exchange")
print("")
print("   GLSL Example (parallel reduction):")
print("   float sum = subgroupAdd(local_value);")
print("   if (subgroupElect()) {")
print("       output[gl_WorkGroupID.x] = sum;")
print("   }")
print("")

print("=" * 55)
print("7. MIPMAP OPERATIONS")
print("=" * 55)
print("   • Multi-resolution image processing")
print("   • Useful for feature pyramids")
print("   • LOD (Level of Detail) selection")
print("")
print("   Available shaders:")
print("   • read_from_mipmaps.spv")
print("   • write_to_mipmaps.spv")
print("")
print("   Use cases:")
print("   • Image pyramid construction")
print("   • Multi-scale feature extraction")
print("   • Progressive loading")
print("")

print("=" * 55)
print("8. MULTI-DISPATCH PATTERNS")
print("=" * 55)
print("   Sequential dispatches (dependent):")
print("   vkCmdDispatch(cmd, groups_x, groups_y, groups_z);")
print("   vkCmdPipelineBarrier(cmd, ...); // Wait for completion")
print("   vkCmdDispatch(cmd, groups_x2, groups_y2, groups_z2);")
print("")
print("   Parallel dispatches (independent):")
print("   • No barrier between dispatches")
print("   • GPU schedules optimally")
print("   • Use for independent operations")
print("")
print("   Indirect dispatch:")
print("   • vkCmdDispatchIndirect()")
print("   • Dispatch size from GPU buffer")
print("   • Dynamic workloads without CPU roundtrip")
print("")

print("=" * 55)
print("9. COMMAND BUFFER STRATEGIES")
print("=" * 55)
print("   Recording strategies:")
print("   • Single command buffer: Simple, re-record each frame")
print("   • Multiple command buffers: Pre-record, cycle through")
print("   • Secondary command buffers: Reusable command sequences")
print("")
print("   ML pipeline pattern:")
print("   cmd = BeginCommandBuffer()")
print("   for layer in model.layers:")
print("       BindPipeline(cmd, layer.shader)")
print("       BindDescriptorSets(cmd, layer.buffers)")
print("       PushConstants(cmd, layer.params)")
print("       Dispatch(cmd, layer.groups)")
print("       if layer.needs_sync:")
print("           PipelineBarrier(cmd)")
print("   EndCommandBuffer(cmd)")
print("   Submit(cmd)")
print("")

print("=" * 55)
print("AVAILABLE ADVANCED SHADERS")
print("=" * 55)
print("   Push Constants:")
print("   • add_shader_with_push_constants.spv")
print("   • add_shader_unstructured_push_constants.spv")
print("")
print("   Tensor Operations:")
print("   • tensor.spv")
print("   • tensor_shader.spv")
print("   • tensor_all_access.spv")
print("   • tensor_write_fixed.spv")
print("")
print("   Image Operations:")
print("   • image_shader.spv")
print("   • copy_img_shader.spv")
print("   • read_from_mipmaps.spv")
print("   • write_to_mipmaps.spv")
print("")
print("   Samplers (various formats):")
print("   • passthrough_glsl_sampler.spv")
print("   • passthrough_RGBA16.spv")
print("   • passthrough_RG16.spv")
print("   • passthrough_depth.spv")
print("")

print("=" * 55)
print("PERFORMANCE TIPS")
print("=" * 55)
print("   1. Batch small dispatches into larger ones")
print("   2. Use push constants for per-layer params")
print("   3. Minimize descriptor set switches")
print("   4. Profile with --profiling-dump-path")
print("   5. Use pipeline cache (--pipeline-caching)")
print("   6. Align buffer sizes to 256 bytes")
print("   7. Prefer FP16 when accuracy permits")
print("   8. Use subgroup ops for reductions")
print("")
EOF

echo ""
echo "To explore shaders in SDK:"
echo "  ls builds/ARM-ML-SDK-Complete/shaders/"
echo ""
echo "To run with profiling:"
echo "  ./builds/ARM-ML-SDK-Complete/bin/scenario-runner \\"
echo "      --scenario test.json \\"
echo "      --profiling-dump-path /tmp/profile.json \\"
echo "      --pipeline-caching"
echo ""
echo "Tutorials completed! Full reference:"
echo "  1. Model analysis"
echo "  2. Compute shaders"
echo "  3. Benchmarking"
echo "  4. Style transfer"
echo "  5. Optimizations"
echo "  6. Advanced Vulkan (this tutorial)"
echo ""
echo "Ready to build your ML pipeline!"
